services:
    client:
        build: ./client
        ports:
            - 8000:3000
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./client/src/:/client/src/    
        depends_on:
            - backend
    backend:
        build: ./server
        ports:
            - 5050:5000
        environment:
            CHOKIDAR_USEPOLLING: "true"    
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/
        depends_on:
            - db
    db:
        image: mongo 
        volumes: 
            - ./data:/data/db
